### ISSUE TITLE
[Bug]: composer command does not work 

### ISSUE THREAD

**Issue by rabol** [spatie/laravel-passkeys#3]
### What happened?

The composer command to install the package does not work 

### How to reproduce the bug

Just copy and paste the composer command and execute it in a terminal 

### Package Version

0

### PHP Version

8.3.11

### Laravel Version

11.23

### Which operating systems does with happen with?

macOS

**Comment by rabol** [comment]
adding this to my composer.json

```
"repositories": [
        {
          "type": "vcs",
          "url": "https://github.com/spatie/laravel-passkeys.git"
        }
      ]
```

made it possible to install the package, but that's not the normal way - looks like the package is not yet registered on https://packagist.org/

**Comment by jhg** [comment]
Maybe they are waiting to register it later, when they think it's ready to be used, as in the [README.md](https://github.com/spatie/laravel-passkeys/blob/main/README.md?plain=1#L1) it tells:

> THIS PACKAGE IS IN DEVELOPMENT, DO NOT USE (YET)
